setting:
  binWidth: 128
  label: 1
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: [1, 1, 1]
  weightingNorm: 

imageType:
  Original: {}

featureClass:
  shape: ['VoxelVolume', 'SurfaceArea', 'SurfaceVolumeRatio', 'Sphericity']
  firstorder: ['Mean', 'StandardDeviation']
  glcm: ['Contrast', 'Correlation', 'Energy', 'InverseVariance']
  glszm: ['LargeAreaEmphasis']
